SELECT * FROM CIS655_MAIN.WORLD.COUNTRY_LANGUAGES;

-- PK columns:
/* COUNTRYCODE, LANGUAGE */

-- Partial key dependencies:
/* COUNTRYCODE --> CountryName, Continent, Region, SurfaceArea, Pop, CapitalCityID, CapitalName, CapitalDistrict, CapitalPop */
/* LANGUAGE --> Nothing! */

-- Full Key dependencies:
/* COUNTRYCODE, LANGUAGE --> IsOfficial, Percentage */

-- Transitive dependencies:
/* CapitalCityID --> CapitalName, CapitalDistrict, CapitalPop (CountryCode, CountryName, Continent, Region, SurfaceArea, Pop)*/
/* Region --> Continent */

-- Recreate COUNTRY table structure from last week if necessary
create or replace TABLE COUNTRY_2NF (
COUNTRYCODE VARCHAR(16777216) PRIMARY KEY,
COUNTRYNAME VARCHAR(16777216),
CONTINENT VARCHAR(16777216),
REGION VARCHAR(16777216),
SURFACEAREA NUMBER(38,2),
COUNTRYPOPULATION NUMBER(38,0),
GNP NUMBER(38,2),
CAPITALCITYID NUMBER(38,0),
CAPITALNAME VARCHAR(16777216),
CAPITALDISTRICT VARCHAR(16777216),
CAPITALPOPULATION NUMBER(38,0)
);

INSERT INTO country_languages_2nf
select countrycode, language, isofficial, percentage from cis655_main.world.country_languages;

INSERT INTO country_2nf
select distinct COUNTRYCODE, COUNTRYNAME, CONTINENT, REGION, SURFACEAREA, COUNTRYPOPULATION, GNP, CAPITALCITYID, CAPITALNAME, CAPITALDISTRICT, CAPITALPOPULATION FROM cis655_main.world.country_languages;

-- Create Capital Entity Table
CREATE OR REPLACE TABLE CAPITAL_3NF (
CAPITALCITYID NUMBER(38,0) PRIMARY KEY,
CAPITALNAME VARCHAR(16777216),
CAPITALDISTRICT VARCHAR(16777216),
CAPITALPOPULATION NUMBER(38,0)
);

-- Create 3NF version of Country
CREATE OR REPLACE TABLE COUNTRY_3NF (
COUNTRYCODE VARCHAR(16777216) PRIMARY KEY,
COUNTRYNAME VARCHAR(16777216),
CONTINENT VARCHAR(16777216),
REGION VARCHAR(16777216),
SURFACEAREA NUMBER(38,2),
COUNTRYPOPULATION NUMBER(38,0),
GNP NUMBER(38,2),
CAPITALCITYID NUMBER(38,0),
CONSTRAINT FK_CAPITAL
FOREIGN KEY (CAPITALCITYID) REFERENCES CAPITAL_3NF (CAPITALCITYID)
);

-- NOW WE CAN PUT DATA INTO THE TABLES
TRUNCATE CAPITAL_3NF;
TRUNCATE COUNTRY_3NF;

INSERT INTO CAPITAL_3NF
SELECT DISTINCT CAPITALCITYID, CAPITALNAME, CAPITALDISTRICT, CAPITALPOPULATION
FROM COUNTRY_2NF;

INSERT INTO COUNTRY_3NF
SELECT DISTINCT COUNTRYCODE, COUNTRYNAME, CONTINENT, REGION, SURFACEAREA, COUNTRYPOPULATION, GNP, CAPITALCITYID
FROM COUNTRY_2NF;
